name: Platane/snk@v3

on:
  workflow_dispatch:

  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Platane/snk action
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.Azlaan20 }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Set up environment variables
        env:
          GITHUB_TOKEN: ${{ secrets.YOUR_SECRET_TOKEN }}
